### ISSUE TITLE
Skin tone does not work in the example

### ISSUE THREAD

**Issue by hoiles** [selemondev/nuxt-emoji-picker#13]
Skin tone does not work in the example neither in the original source vue3-emoji-picker

1. Go to ['example'](https://stackblitz.com/edit/nuxt-starter-qstqbs?file=app.vue)
2. Click on 'Skin tones'
3. Change skin tones
4. Emojis stay the same yellow color

**Expected behavior**
Emojis change color and selected emoji is also with the yellow color

![Screenshot 2024-08-29 at 2 16 47 PM](https://github.com/user-attachments/assets/44135125-32e9-4576-9aab-4c54a6fc4da3)

**Comment by selemondev** [comment]
Hey there @lesliehoiagency, thanks for creating this issue. From your example above, scroll to the bottom and you will see the tone in effect. The yellow emojis don't change in skin tone but the `humans` do change.
